DummyAirport/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

import passengers.urls
import flights.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('', include(passengers.urls)),
    path('', include(flights.urls, namespace='flights')),
]

flights/urls.py
from django.urls import path, include

from .views import FlightsListView, FlightDetailView

app_name = 'flights'

urlpatterns = [
    path('flights/', FlightsListView.as_view(), name='list'),
    path('flights/<slug:flight_code>/', FlightDetailView.as_view(), name='detail')
]

passengers/urls.py
from django.urls import path, include

from .views import PassengerProfileView


urlpatterns = [
    path('accounts/profile/', PassengerProfileView.as_view(), name='profile')
]

companies/models.py
from django.db import models

from planes.models import Plane


class Company(models.Model):
    name = models.CharField(max_length=15, db_index=True, unique=True)
    caption = models.TextField()
    planes = models.ManyToManyField(Plane)

    class Meta:
        db_table = 'companies'
        ordering = ['name']

    def __str__(self):
        return self.name


class ServiceClasses(models.Model):
    SERVICE_LEVELS = (
        ('EC', 'Economy'), ('ST', 'Standart'), ('BS', 'Business')
    )

    company = models.ManyToManyField(Company)
    service_level = models.CharField(max_length=15, choices=SERVICE_LEVELS, db_index=True)
    max_light_baggage_weight = models.PositiveSmallIntegerField()
    max_big_baggage_weight = models.PositiveSmallIntegerField()
    max_baggage_size = models.PositiveSmallIntegerField()
    allow_ticket_return = models.BooleanField(db_index=True)
    price = models.PositiveIntegerField()

    class Meta:
        db_table = 'service_classes'

    def __str__(self):
        return f'{self.company} - {self.service_level}'

flights/models.py
from django.db import models

from passengers.models import Passenger
from companies.models import Company
from planes.models import Plane


class Flight(models.Model):
    flight_code = models.CharField(max_length=10, db_index=True)
    departure_city = models.CharField(max_length=20, db_index=True)
    arrival_city = models.CharField(max_length=20, db_index=True)
    departure_time = models.DateTimeField()
    arrival_time = models.DateTimeField()
    distance = models.PositiveSmallIntegerField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    plane = models.ForeignKey(Plane, on_delete=models.SET_NULL, null=True)

    class Meta:
        db_table = 'flights'
        ordering = ['departure_time']

    def __str__(self):
        return f'{self.flight_code}'

    @property
    def duration(self):
        return self.arrival_time - self.departure_time


class Registration(models.Model):
    passenger = models.OneToOneField(Passenger, on_delete=models.CASCADE)
    flight = models.OneToOneField(Flight, on_delete=models.CASCADE)
    registration_time = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        db_table = 'flight_registration'
        ordering = ['registration_time']

    def __str__(self):
        return f'{self.passenger.full_name} - {self.flight.flight_code}'

passengers/models.py
from django.db import models
from django.contrib.auth.models import User


class Passenger(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=12, db_index=True)
    last_name = models.CharField(max_length=15, db_index=True)
    birth_date = models.DateField()
    passport_number = models.CharField(max_length=12, db_index=True)

    class Meta:
        db_table = 'passengers'

    def __str__(self):
        return self.full_name

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

planes/models.py
from django.db import models


class Plane(models.Model):
    model = models.CharField(max_length=12, db_index=True, unique=True)
    country = models.CharField(max_length=15)
    load_capacity = models.PositiveSmallIntegerField()
    fuel_capacity = models.PositiveSmallIntegerField()
    passengers_capacity = models.PositiveSmallIntegerField(db_index=True)
    description = models.TextField()

    class Meta:
        db_table = 'planes'

timeline/models.py
from django.db import models

from flights.models import Flight


class Timeline(models.Model):
    AWAITING_CHECK_IN = ('AC', 'Awaiting check-in')
    CHECK_IN = ('C', 'Check-in')
    CHECK_IN_OVER = ('CO', 'Check-in is over')
    REJECTED = ('R', 'Rejected')
    DELAYED = ('D', 'Delayed')
    BOARDING = ('B', 'Boarding')
    GATE_CLOSED = ('GC', 'Gate closed')
    IN_FLIGHT = ('F', 'In flight')
    ARRIVED = ('A', 'Arrived')

    FLIGHT_STATUSES = (
        AWAITING_CHECK_IN,
        CHECK_IN_OVER,
        CHECK_IN,
        REJECTED,
        DELAYED,
        BOARDING,
        GATE_CLOSED,
        IN_FLIGHT,
        ARRIVED
    )

    flight = models.ForeignKey(Flight, on_delete=models.CASCADE)
    terminal = models.CharField(max_length=5)
    flight_status = models.CharField(max_length=20, choices=FLIGHT_STATUSES, default=AWAITING_CHECK_IN, db_index=True)
    gate = models.CharField(max_length=5, null=True, blank=True, db_index=True)

    class Meta:
        db_table = 'timeline'

    def __str__(self):
        return f'{self.flight.flight_code} - {self.flight_status}'

companies/views.py
from django.shortcuts import render

# Create your views here.

flights/views.py
from django.views.generic import ListView, DetailView

from .models import Flight


class FlightsListView(ListView):
    template_name = 'flights_list.html'
    queryset = Flight.objects.all()
    context_object_name = 'flights'


class FlightDetailView(DetailView):
    template_name_suffix = ''
    template_name = 'flights_detail.html'
    model = Flight
    context_object_name = 'flight'
    slug_field = 'flight_code'
    slug_url_kwarg = 'flight_code'

passengers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from .models import Passenger


class PassengerProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'profile_view.html'
    redirect_field_name = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = Passenger.objects.get(pk=self.request.user.id)
        return context

planes/views.py
from django.shortcuts import render

# Create your views here.

timeline/views.py
from django.shortcuts import render

# Create your views here.

flights/templates/flights_detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="dashboard">
    <div class="card">
        <h5 class="card-header">Flight "{{ flight.flight_code }}" info:</h5>
        <div class="card-body">
            <p class="card-text">Departure city: {{ flight.departure_city }} </p>
            <p class="card-text">Arrival city: {{ flight.arrival_city }} </p>
            <p class="card-text">Departure time: {{ flight.departure_time }} </p>
            <p class="card-text">Arrival time: {{ flight.arrival_time }} </p>
            <p class="card-text">Company: {{ flight.company.name }} </p>
            <p class="card-text">Plane: {{ flight.plane.model }} </p>
            <p class="card-text">Distance: {{ flight.distance }} </p>
            <p class="card-text">Duration: {{ flight.duration}} </p>
        </div>
    </div>
</div>

{% endblock %}


</body>
</html>

flights/templates/flights_list.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flights</title>
</head>
<body>
{% block content %}
    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Flight</th>
      <th scope="col">Departure city</th>
        <th scope="col">Arrival city</th>
        <th scope="col">Departure time</th>
        <th scope="col">Arrival time</th>
    </tr>
  </thead>
  <tbody>
  {% for flight in flights %}
    <tr>
      <td><a href={% url 'flights:detail' flight.flight_code %}>{{ flight.flight_code }}</a></td>
      <td>{{ flight.departure_city }}</td>
      <td>{{ flight.arrival_city }}</td>
      <td>{{ flight.departure_time }}</td>
      <td>{{ flight.arrival_time }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}
</body>
</html>

passengers/templates/profile_view.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="dashboard">
    <div class="card">
        <h5 class="card-header">Passenger info:</h5>
        <div class="card-body">
            <p class>First name: {{ profile.first_name }} </p>
            <p class="card-text">Last name: {{ profile.last_name }} </p>
            <p class="card-text">Birth date: {{ profile.birth_date }} </p>
            <p class="card-text">Passport number: {{ profile.passport_number }} </p>
        </div>
    </div>
</div>

{% endblock %}


</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Airport</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
{% include 'navbar.html' %}
{% block content %}

{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action={% url 'login' %}>
{% csrf_token %}
{{ form.as_p }}
<button type="submit">OK</button>
</form>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">DummyAirport</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only"></span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Timeline</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href={% url 'flights:list' %}>Flights</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Companies</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Planes</a>
        </li>
    </ul>
    </div>
</nav>